name: learn-github-actions
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        #with:
                #Enode-version: '14'
      - run: pip install pytest install git+https://github.com/nih-megcore/nih_to_mne
      - run: pytest -vv
